XoTT_Auction.Web/ViewModels/LotsViewModels.cs
using XoTT_Auction.DAL.Models;
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations;

namespace XoTT_Auction.Web.ViewModels
{
    /// <summary>
    /// class to display all lots and categories
    /// </summary>
    public class LotsListingViewModel : PageViewModel
    {
        public List<Lot> Lots { get; set; }

        public Pager Pager { get; set; }

        public string SearchTerm { get; set; }
        public int? PageNo { get; set; }
        public int? CategoryId { get; set; }

        public List<Category> Categories { get; set; }
    }
    /// <summary>
    /// class to display one lot and bid
    /// </summary>
    public class LotDetailsViewModel : PageViewModel
    {
        public Lot Lot { get; set; }
        public decimal BidsAmount { get; set; }

        public User LatestBidder { get; set; }
    }
    /// <summary>
    /// class for creating and editing lots
    /// </summary>
    public class LotViewModel : PageViewModel
    {
        public int Id { get; set; }
        [Required]
        [MinLength(15), MaxLength(150)]
        public string Title { get; set; }
        public string Description { get; set; }
        [Required]
        [Range(1, 15000)]
        public decimal StartPrice { get; set; }
        [Required]
        [Range(1, 10)]
        public decimal Step { get; set; }

        public DateTime? StartingTime { get; set; }
        public DateTime? EndingTime { get; set; }
        public string LotPictures { get; set; }

        public int CategoryId { get; set; }
        public Category Category { get; set; }

        public virtual Lot Lot { get; set; }
        public virtual List<Category> Categories { get; set; }
    }
}

XoTT_Auction.Web/Controllers/BidsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using XoTT_Auction.BLL.Interfaces;
using XoTT_Auction.DAL.Models;

namespace XoTT_Auction.Web.Controllers
{
    [Authorize]
    public class BidsController : Controller
    {
        private readonly IBidsService _bidsService;
        private readonly ILotsService _lotsService;
        public BidsController(IBidsService bidsService, ILotsService lotsService)
        {
            _bidsService = bidsService;
            _lotsService = lotsService;
        }
        [Authorize(Roles = "User")]
        public async Task<JsonResult> Bid(int lotId)
        {
            try
            {
                JsonResult result = new JsonResult
                {
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };

                var lot = _lotsService.GetLotById(lotId);

                Bid bid = new Bid
                {
                    LotId = lotId,
                    UserId = User.Identity.GetUserId(),
                    Timestamp = DateTime.Now,
                    BidAmount = lot.Step
                };

                var bidResult = await _bidsService.CreateAsync(bid);

                if (bidResult)
                {
                    result.Data = new { success = true };
                }
                else
                {
                    result.Data = new { success = false, message = "Failed to add a bid" };
                }
                return result;
            }
            catch
            {
                JsonResult result = new JsonResult();
                result.Data = new { success = false, message = "An error has occurred, please try again" };
                return result;
            }
        }
    }
}

XoTT_Auction.Web/Controllers/LotsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using XoTT_Auction.DAL.Models;
using XoTT_Auction.Web.ViewModels;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using XoTT_Auction.Web.Filters;
using XoTT_Auction.BLL.Interfaces;

namespace XoTT_Auction.Web.Controllers
{
    [Authorize]
    [CheckIfUserIsBanned]
    public class LotsController : Controller
    {
        private readonly ILotsService _lotsService;
        private readonly ICategoriesService _categoriesService;
        public LotsController(ILotsService lotService,
            ICategoriesService categoriesService) 
        {
            _lotsService = lotService;
            _categoriesService = categoriesService;
        }

        public ActionResult Index(int? categoryId, string searchTerm, int? pageNo)
        {
            try
            {
                var lots = new LotsListingViewModel
                {
                    PageTitle = "Lots",
                    PageDescription = "This is Lots Page",

                    CategoryId = categoryId,
                    SearchTerm = searchTerm,
                    PageNo = pageNo
                };
                lots.Categories = _categoriesService.GetAll();
                return View(lots);
            }
            catch
            {
                var error = new ListOfErrorsViewModel
                {
                    PageTitle = "Error Page",
                    PageDescription = "This is Error Page",
                    Errors = new string[] { "An error has occurred, please try again" }
                };
                return View("Error", error);
            }
        }

        public PartialViewResult Listing(int? categoryId, string searchTerm, int? pageNo) 
        {
            try
            {
                var pageSize = 5;
                pageNo = pageNo ?? 1;

                string userId = null;
                if (!User.IsInRole("Admin"))
                {
                    userId = User.Identity.GetUserId();
                }

                var lotsModel = new LotsListingViewModel
                {
                    Lots = _lotsService.FilterLots(categoryId, pageNo, pageSize, searchTerm, userId)
                };

                var totalLots = _lotsService.GetFilteredLotsCount(categoryId, searchTerm);

                lotsModel.Pager = new Pager(totalLots, pageNo, pageSize);

                lotsModel.CategoryId = categoryId;
                lotsModel.SearchTerm = searchTerm;

                return PartialView(lotsModel);
            }
            catch
            {
                var error = new ListOfErrorsViewModel
                {
                    PageTitle = "Error Page",
                    PageDescription = "This is Error Page",
                    Errors = new string[] { "An error has occurred, please try again" }
                };
                return PartialView("Error", error);
            }
        }

        [AllowAnonymous]
        public async Task<ActionResult> Details(int id)
        {
            try
            {
                var model = new LotDetailsViewModel
                {
                    PageTitle = "Details Page",
                    PageDescription = "This is Details Page",
                    Lot = await _lotsService.GetLotByIdAsync(id)
                };
                model.BidsAmount = model.Lot.StartPrice
                    + model.Lot.Bids.Sum(b => b.BidAmount);
                var latestBidder = model.Lot.Bids
                    .OrderByDescending(b => b.Timestamp)
                    .FirstOrDefault();
                model.LatestBidder = latestBidder?.User;
                return View(model);
            }
            catch
            {
                var error = new ListOfErrorsViewModel
                {
                    PageTitle = "Error Page",
                    PageDescription = "This is Error Page",
                    Errors = new string[] { "An error has occurred, please try again" }
                };
                return View("Error", error);
            }        
        }



        [Authorize(Roles = "User")]
        public async Task<ActionResult> Create()
        {
            try
            {
                var model = new LotViewModel
                {
                    Categories = await _categoriesService.GetAllAsync()
                };
                return PartialView(model);
            }
            catch
            {
                var error = new ListOfErrorsViewModel
                {
                    PageTitle = "Error Page",
                    PageDescription = "This is Error Page",
                    Errors = new string[] { "An error has occurred, please try again" }
                };
                return View("Error", error);
            }
        }



        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Create(LotViewModel model)
        {
            try
            {
                JsonResult result = new JsonResult();

                if (ModelState.IsValid)
                {

                    Lot newLot = new Lot
                    {
                        Title = model.Title,
                        Description = model.Description,
                        StartPrice = model.StartPrice,
                        Step = model.Step,
                        StartingTime = model.StartingTime,
                        EndingTime = model.EndingTime,
                        CategoryId = model.CategoryId,
                        UserId = User.Identity.GetUserId()
                    };

                    if (!string.IsNullOrEmpty(model.LotPictures))
                    {
                        var pictureIds = model.LotPictures.Split(',').Select(int.Parse);
                        var list = new List<LotPicture>();
                        list.AddRange(pictureIds
                            .Select(pi => new LotPicture() { PictureId = pi }));
                        newLot.LotPictures = list;
                    }
                    await _lotsService.CreateLotAsync(newLot);

                    result.Data = new { success = true };
                }
                else
                {
                    result.Data = new { success = false, message = "Invalid inputs." };
                }

                return result;
            }
            catch
            {
                JsonResult result = new JsonResult();
                result.Data = new { success = false, message = "An error has occurred, please try again" };
                return result;
            }
            
        }


        [Authorize(Roles = "User")]
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var model = new LotViewModel
                {
                    Lot = await _lotsService.GetLotByIdAsync(id),
                    Categories = await _categoriesService.GetAllAsync()
                };

                return PartialView(model);
            }
            catch
            {
                var error = new ListOfErrorsViewModel
                {
                    PageTitle = "Error Page",
                    PageDescription = "This is Error Page",
                    Errors = new string[] { "An error has occurred, please try again" }
                };
                return View("Error", error);
            }
        }




        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Edit(LotViewModel model)
        {
            try
            {
                JsonResult result = new JsonResult();

                if (ModelState.IsValid)
                {
                    var lot = new Lot
                    {
                        Id = model.Id,
                        Title = model.Title,
                        Description = model.Description,
                        StartPrice = model.StartPrice,
                        Step = model.Step,
                        StartingTime = model.StartingTime,
                        EndingTime = model.EndingTime,
                        CategoryId = model.CategoryId,
                        UserId = User.Identity.GetUserId()
                    };

                    if (!string.IsNullOrEmpty(model.LotPictures))
                    {
                        var pictureIds = model.LotPictures.Split(',').Select(int.Parse);

                        var list = new List<LotPicture>();
                        list.AddRange(pictureIds.Select(pi => new LotPicture()
                        {
                            PictureId = pi,
                            LotId = lot.Id
                        }).ToList());
                        lot.LotPictures = list;
                    }

                    await _lotsService.UpdateLotAsync(lot);

                    result.Data = new { success = true };
                }
                else
                {
                    result.Data = new { success = false, message = "Invalid inputs." };
                }

                return result;
            }
            catch
            {
                JsonResult result = new JsonResult();
                result.Data = new { success = false, message = "An error has occurred, please try again" };
                return result;
            }
            
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _lotsService.DeleteLotAsync(id);
                return RedirectToAction("Listing");
            }
            catch
            {
                var error = new ListOfErrorsViewModel
                {
                    PageTitle = "Error Page",

XoTT_Auction.Web/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using XoTT_Auction.BLL.Interfaces;
using XoTT_Auction.DAL.Models;

namespace XoTT_Auction.Web.Controllers
{
    [Authorize]
    public class PicturesController : Controller
    {
        private readonly IPicturesService _pictureService;
        public PicturesController(IPicturesService pictureService)
        {
            _pictureService = pictureService;
        }

        [HttpPost]
        public async Task<JsonResult> UploadPictures()
        {
            try
            {
                JsonResult result = new JsonResult();

                List<object> picturesJSON = new List<object>();

                var pictures = Request.Files;

                for (int i = 0; i < pictures.Count; i++)
                {
                    var picture = pictures[i];

                    var fileName = Guid.NewGuid() + Path.GetExtension(picture.FileName);

                    var path = Server.MapPath("~/Content/images/") + fileName;

                    picture.SaveAs(path);

                    var dbPicture = new Picture
                    {
                        URL = fileName
                    };

                    int pictureId = await _pictureService.SavePictureAsync(dbPicture);

                    picturesJSON.Add(new { Id = pictureId, URL = fileName });
                }

                result.Data = picturesJSON;

                return result;
            }
            catch
            {
                JsonResult result = new JsonResult();
                result.Data = new { success = false, message = "An error has occurred, please try again" };
                return result;
            }
        }
    }
}

XoTT_Auction.Web/Views/Lots/Create.cshtml
@model XoTT_Auction.Web.ViewModels.LotViewModel

<div class="modal-header">
    <h5 class="modal-title">Create Lot</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form id="createForm">
    @Html.AntiForgeryToken()
    <div class="modal-body">

        <label for="Title">Title</label>
        <div class="input-group mb-1">
            <input type="text" class="form-control" name="Title" id="Title" value="@Model.Title" />
        </div>

        <div class="mb-1">
            <label for="Title">Category</label>
            <select class="form-select" name="CategoryId">
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.Id">@category.Name</option>
                }
            </select>
        </div>

        <div class="mb-1">
            <label for="Description">Description</label>
            <input type="text" class="form-control" name="Description" id="Description" value="@Model.Description" />
        </div>

        <label for="StartPrice">Start Price</label>
        <div class="input-group mb-1">
            <span class="input-group-text">$</span>
            <input type="number" class="form-control" name="StartPrice" id="StartPrice" value="@Model.StartPrice" min="0" />
        </div>

        <label for="Step">Bid Step</label>
        <div class="input-group mb-1">
            <span class="input-group-text">$</span>
            <input type="number" class="form-control" name="Step" id="Step" value="@Model.Step" min="0" />
        </div>

        <div class="mb-1">
            <label for="StartingTime">Starting Time</label>
            <input type="text" class="form-control" name="StartingTime" id="StartingTime" value="@Model.StartingTime" readonly />
        </div>

        <div class="mb-1">
            <label for="EndingTime">Ending Time</label>
            <input type="text" class="form-control" name="EndingTime" id="EndingTime" value="" readonly />
        </div>

        <div class="mb-1">
            <label for="selectPictures" class="btn btn-info" style="cursor:pointer">
                Select Pictures
                <span id="fileLength" class="badge p-1" style="display:none"></span>
            </label>
            <span id="picTip" style="display:none;" class="float-right badge bg-secondary p-1 mt-2">Press on pic to remove it</span>
            <input type="file" class="form-control" name="LotPictures" id="selectPictures" style="display:none" multiple="multiple" />
            <input type="hidden" id="pictureIds" name="LotPictures" />
            <div id="picsArea" class="m-2"></div>
        </div>
        <div id="divError" class="mb-1 alert alert-danger" style="display:none;">
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id="saveBtn">Save</button>
    </div>
</form>

<script>
    var d = new Date();
    var month = d.getMonth() + 1;
    var day = d.getDate();

    var currentDate = (month < 10 ? '0' : '') + month + '/' + (day < 10 ? '0' : '') + day + '/' + d.getFullYear();

    $('input[name="StartingTime"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        drops: 'up',
        minDate: currentDate,
        timePicker: true,
        minYear: parseInt(moment().format('YYYY')),
        maxYear: parseInt(moment().format('YYYY'), 11),
        locale: {
            format: 'M/DD/YYYY hh:mm A',
        }
    });

    $('input[name="EndingTime"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true,
        drops: 'up',
        minDate: currentDate,
        timePicker: true,
        minYear: parseInt(moment().format('YYYY')),
        maxYear: parseInt(moment().format('YYYY'), 11),
        locale: {
            format: 'M/DD/YYYY hh:mm A',
        }
    });

    $("#createForm").validate({
        rules: {
            Title: {
                required: true,
                minlength: 15,
                maxlength: 150
            },
            StartPrice: {
                required: true,
                range: [1, 15000]
            },
            Step: {
                required: true,
                range: [1, 10]
            }
        },
        messages: {
            Title: {
                required: "Title is required.",
                minlength: "Minimum length is 15",
                maxlength: "Maximum length is 150"
            },
            StartPrice: {
                required: "Start price is required.",
                range: "Start price must be in range from 1 to 15000."
            },
            Step: {
                required: "Bid step price is required.",
                range: "Bid step price must be in range from 1 to 10."
            }
        },
        errorClass: "text-danger input-group-text"
    })

    $("#StartPrice").change(function () {
        this.value = this.value.replace(/[e\+\-\.]/gi, "");
        if (this.value > 15000) this.value = 15000;
    })

    $("#Step").change(function () {
        this.value = this.value.replace(/[e\+\-\.]/gi, "");
        if (this.value > 10) this.value = 10;
    })

    $("#saveBtn").click(function () {
        debugger;
        if ($("#createForm").valid()) {
            var picIds = [];

            $("#picsArea .image").each(function () {
                var picId = $(this).attr("data-id");

                picIds.push(picId);
            })

            $("#pictureIds").val(picIds);

            $.ajax({
                url: '@Url.Action("Create","Lots")',
                type: 'Post',
                data: $("#createForm").serialize(),
            }).done(function (response) {
                if (response.success) {
                    ReloadListing()
                    $("#formModal").modal("toggle");
                } else {
                    $("#divError").html(response.message);
                    $("#divError").show();
                }
            }).fail(function (xhr) {
                alert('Fail');
            });
        }
    })

    $("#selectPictures").change(function () {
        var pictures = this.files;
        var picsLength = pictures.length;

        if (pictures.length > 10) {
            alert("Not allowed to upload more than 10 pictures in one time.");
            picsLength = 10;
        }

        var picsData = new FormData();

        for (var i = 0; i < picsLength; i++) {
            picsData.append("Picture", pictures[i]);
        }
        $.ajax({
            url: '@Url.Action("UploadPictures", "Pictures")',
            type: 'Post',
            data: picsData,
            processData: false,
            contentType: false
        }).done(function (responses) {
            for (var i = 0; i < responses.length; i++) {
                var picResponse = responses[i];

                AttachNewImage(picResponse.Id, picResponse.URL);
            }
            //print length of pictures, if exist one override it.
            var oldLength;
            var newLength;
            if ($("#fileLength").text()) {
                oldLength = $("#fileLength").text()[0];
                newLength = parseFloat(oldLength) + parseFloat(picsLength);
                $("#fileLength").empty();
            } else {
                newLength = picsLength; //first time
            }
            $("#fileLength").append(newLength + " pictures. ");
            $("#fileLength").show();
        }).fail(function () {
            alert("Fail");
        });
    })
</script>

XoTT_Auction.Web/Views/Lots/Details.cshtml
@model XoTT_Auction.Web.ViewModels.LotDetailsViewModel
@using Microsoft.AspNet.Identity;

<div class="row">

    <div class="col-lg-12">

        <div class="card mt-4">

            @if (Model.Lot.LotPictures != null && Model.Lot.LotPictures.Count() > 0)
            {
                var firstLotPicture = Model.Lot.LotPictures.First();

                var i = 0;
                <div id="carouselIndicators" class="carousel slide " data-bs-ride="carousel">
                    <ol class="carousel-indicators">
                        @foreach (var lotPicture in Model.Lot.LotPictures)
                        {
                            var active = lotPicture == firstLotPicture ? "active" : string.Empty;

                            <li class="@active" data-bs-target="#carouselIndicators" data-bs-slide-to="@i"></li>
                            i++;
                        }
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        @foreach (var lotPicture in Model.Lot.LotPictures)
                        {
                            var active = lotPicture == firstLotPicture ? "active" : string.Empty;

                            var picURL = "/Content/images/" + lotPicture.Picture.URL;

                            <div class="carousel-item @active">
                                <img class="d-block img-thumbnail img-fluid mx-auto" src="@picURL" style="height: 250px;" />
                            </div>
                        }
                    </div>
                    <a class="carousel-control-prev" data-bs-target="#carouselIndicators" type="button" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </a>
                    <a class="carousel-control-next" data-bs-target="#carouselIndicators" type="button" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </a>
                </div>
            }

        <div class="card-body">
            <h3 class="card-title">@Model.Lot.Title</h3>
            <h4>
                $@Model.BidsAmount
                @if (Model.LatestBidder != null)
                {
                    <span class="badge bg-secondary p-1">[ Latest bidder: @Model.LatestBidder.UserName ]</span>
                }
            </h4>

            <p class="card-text">@Model.Lot.Description</p>

            @{
                var datRes = Model.Lot.EndingTime - DateTime.Now;
                var result = (int)datRes.Value.TotalMinutes;
                if (result <= 0)
                {
                    @:<h6 class="text-danger fw-bold">Lot is finished</h6>
                }
                else if (result >= 60)
                {
                    var hours = result / 60;
                    @:<h6 class="fw-bold">@hours hours left</h6>
                }
                else
                {
                    @:<h6 class="fw-bold">@result minutes left</h6>
                }
            }

        </div>

            @if (!User.Identity.IsAuthenticated)
            {
                <div class="card-footer text-muted">
                    <button id="bidBtn" type="button" class="btn btn-primary">Bid now (Bid step: $@Model.Lot.Step)</button>
                </div>
            }
            else if (Model.Lot.UserId != User.Identity.GetUserId() && Model.LatestBidder?.Id != User.Identity.GetUserId())
            {
                <div class="card-footer text-muted">
                    <button id="bidBtn" type="button" class="btn btn-primary">Bid now (Bid step: $@Model.Lot.Step)</button>
                </div>
            }

        </div>

    </div>

</div>

<script>
    $("#bidBtn").click(function () {
        debugger;
        $.ajax({
            url: "@Url.Action("Bid","Bids")",
            type: 'Post',
            data: {
                lotId: '@Model.Lot.Id'
            }
        })
        .done(function (response) {
            if (response.success) {
                window.location.reload();
            } else {
                Swal.fire("Oops!", "Please, login first...", "error");
            }
        })
        .fail(function () {
            Swal.fire("Oops!", "Something went wrong, please try again later.", "error");
        })
    })
</script>

XoTT_Auction.Web/Views/Lots/Listing.cshtml
@model XoTT_Auction.Web.ViewModels.LotsListingViewModel
<table class="table table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Start Price</th>
            <th>Bid Step</th>
            <th>Bids</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Lots != null && Model.Lots.Count() > 0)
        {
            foreach (var lot in Model.Lots)
            {
                <tr>
                    <td>@lot.Title</td>
                    <td>@lot.Category.Name</td>
                    <td>$@lot.StartPrice</td>
                    <td>$@lot.Step</td>
                    @if (lot.Bids != null && lot.Bids.Count() > 0)
                    {
                        <td>@lot.Bids.Count()</td>
                    }
                    else
                    {
                        <td>0</td>
                    }
                    <td>
                        <button data-id="@lot.Id" class="editBtn btn btn-outline-info">Edit</button>
                        <button data-id="@lot.Id" class="deleteBtn btn btn-outline-danger">Delete</button>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6" class="text-center alert alert-danger">No lots found.</td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(".editBtn").click(function () {
        var id = $(this).attr("data-id");
        $.ajax({
            url: '@Url.Action("Edit","Lots")',
            method: 'Get',
            data: {
                id: id,
            }
        })
        .done(function (response) {
            $("#formModal").modal("toggle");
            $("#actionArea").html(response);
        })
        .fail(function (response) {
            debugger;
            alert('Error')
        })
    });

    $(".deleteBtn").click(function () {
        $("#deleteModal").modal("toggle");
        $("#modalDeleteBtn").attr("data-id", $(this).attr("data-id"));
    });
</script>